Repository cardano-foundation/cardano-token-registry, pull requests merged in 2024-08, with the labels that each got.

#6280 Add a New Client Token by SnekX
  mappings/4e610e0ec7a98bfc2ebcfaf52f4037a161a0b615cac24585a1cd40ff504a45455452.json
Labels: checked

#6278 Add a New Client Token by SnekX
  mappings/2a80006eb7c4f453cb9d8e96dba12115f97d7f5f43046017f2705733446567656e.json
Labels: checked

#6275 Add a New Client custom Token
  mappings/a16026a3c4bddea046a83317c2799a23cb7679a86b819fea8dd5311b484f444f52.json
Labels: checked

#6294 Create Goofy token registry
  mappings/79bc81072dd9250d4ac63b8f55fa8670a91d9b0fbd943c57028614de474f4f4659.json
Labels: checked

#6293 Add a New Client Token by SnekX
  mappings/1483b5209db73a7d8f29193d90cfa173b3471a00a7ab3684be13ec57446f676779.json
Labels: checked

#6287 Add a New Client Token by SnekX
  mappings/08c56d8b4baee49c62085647c4fd43ce90c645f69ff72d554f343bda536e656b66756e.json
Labels: checked

#6281 Add files via upload
  mappings/f5d73b63944ec9bac6817995f2811ceb8cfa2828b79ee6701fb65eb0484d59.json
Labels: checked

#6282 Add files via upload
  mappings/03db98ba78e79edab4b314f4fc94d6dbe7ca3279049521a30d09735a504159.json
Labels: checked

#6283 Add files via upload
  mappings/aa521407bb09a548082df4d770f3ea615af2c0a96e9377cd3c8a09d050434e.json
Labels: checked

#6299 Add a New Client Token by SnekX
  mappings/6971d041be5f5d144265e315e3b154a8295dc81b2666f160cc5be45a47696e6765725768616c65.json
Labels: checked

#6297 Add a New Client Token by SnekX
  mappings/aa21aaa2ecce9392fd1d9d676f84407aaf4f36e18e028c83429dc9e147696e6765725768616c65.json
Labels: checked

#6296 Add a New Client Token by SnekX
  mappings/44b5a0c831d42b8c5fd1243da6b084c9469e04c7b931c3a30722b5e747454b4f.json
Labels: checked

#6330 Add a New Client Token by SnekX
  mappings/d1aed155db7ed65dd9a895c43cb1b62eeea1752e4a2472dace73b5e34d454c4c4f.json
Labels: checked

#6311 Add a New Client custom Token
  mappings/e292d2c05c22ce6459be92562a8673c7a45c0ecd61a000fee7f1af68496c6c7573747261746f72.json
Labels: checked

#6306 Add a New Client Token by SnekX
  mappings/c9c326b3908a8d8281a8fcfe96a9ba626e65ea16b0734daf03a17736416461476f6473.json
Labels: checked

#6304 Add a New Client custom Token
  mappings/434056b3602176e84842fc915da26a8a511eafce439bc66a5efb307053414447454e.json
Labels: checked

#6310 Add a New Client custom Token
  mappings/549edfa9c5df827be5ab9dc54d73f8664eca87074e0a54541ab6ecc6536e656b46756e.json
Labels: checked

#6349 Add a New Client Token by SnekX
  mappings/d85f30b8b4c7c8dc18f4566db7ffae6efdd5b693e64be93cb9b97ee3454c4d63446f6e616c646f.json
Labels: checked

#6348 Add a New Client custom Token
  mappings/7860a7226131c9253b9f6e1a5adae77e419561f82b973551668c5bac5249434b.json
Labels: checked

#6347 Add a New Client Token by SnekX
  mappings/107f82a42c42f1ad0001854bcb856b50f86574febf3c8e16d760157654494d.json
Labels: checked

#6344 Add a New Client Token by SnekX
  mappings/ea60fb56d9545e76126de63e4820d6a1ef1c96dd979a9b5c11c3f5484c6965734f6e6c79.json
Labels: checked

#6353 Add a New Client Token by SnekX
  mappings/d708a90edaf1e6f2580ae495362c8af4acaf99473d31705424d1fab94c6965734f6e6c79.json
Labels: checked

#6337 One Time Minter Prod
  mappings/f805db0c98d4be397e01494e74dc8cbda91bbbad36e13763a71ed3f94f6e652054696d65204d696e7465722050726f64.json
Labels: checked, waiting for author

#6361 Add a New Client Token by SnekX
  mappings/c559454d37d1f229ac66636ccdcf0bfde2f46af0f4b69c67780bcf314a454554455250414e.json
Labels: checked

#6362 Add a New Client Token by SnekX
  mappings/440d8cbb07856d595becedd7e8e2149693de3a5019e8c4e4a4702e554a45455453504152524f57.json
Labels: checked

#6417 Add a New Client Token by SnekX
  mappings/339a2e648a9bf176cd5ba45ea0d6056f75646dff55f125898c87359850455045.json
Labels: checked

#6416 Add a New Client custom Token
  mappings/ef168baa497e3481ced65f8d66994cd4d44bd571110a487edb37bc53544f4d4d59.json
Labels: checked

#6398 Add a New Client Token by SnekX
  mappings/6cc611ad14294afc9393ddf2630f4623cd64049579c31b2071582ce64e49514142.json
Labels: checked

#6397 Add a New Client Token by SnekX
  mappings/2a14d49623047259d6c0528255333e44cd6f70aa0cfc43399985fc817465656a.json
Labels: checked

#6395 Add a New Client Token by SnekX
  mappings/48786c996f6e24913c41a2f2227445bc598e92bae7e45e32702f06fa5741524f4652554753.json
Labels: checked

#6394 Add a New Client custom Token
  mappings/27941d5b309d276da68e19eeea92dbe26b178d31b6e66062ddfbfe465741524f4652554753.json
Labels: checked

#6391 Add a New Client Token by SnekX
  mappings/85c947cb2ea0370f95b547e222fd77857781e870367be5dd47e7dba54d696b6579.json
Labels: checked

#6378 Add a New Client custom Token
  mappings/5eb0da33c82c10837f65461d0773715363f654855a65fe10f2c6fbe842554c4c434f494e.json
Labels: checked

#6371 Add a New Client Token by SnekX
  mappings/40a33ad4249e010696742b6dc615e57680d2d66c370810b9cbdeef4b536e656b5361756365.json
Labels: checked

#6421 Add a New Client Token by SnekX
  mappings/dcd019897e2501dd41972f71c99c18d4024d9cade976c9e34f11d9f3534e454b76734a5047.json
Labels: checked

#6390 Update logo - SnekX
  mappings/05c4bcecccff054c9aefff8bdc310e1edb8baa0756d912b47ae45d694d65656d.json
Labels: checked

#6424 Create 9dc05b83ac10a6490dcae16b41b00ccf2a036593f5a1f2b9bedef5e347524e…
  mappings/9dc05b83ac10a6490dcae16b41b00ccf2a036593f5a1f2b9bedef5e347524e5431.json
Labels: waiting for author

#6491 Add a New Client Token by SnekX
  mappings/0754a4588e44ae70246002164d3b56f6242a4eb7dcc9271d98fc038243415244414e4f434142414c.json
Labels: checked

#6488 Add a New Client Token by SnekX
  mappings/677db1b02fe513268151b3ed7bc4a3edddffed16a554f262f8b2970f46576966686174.json
Labels: checked

#6463 Add a new token
  mappings/f805db0c98d4be397e01494e74dc8cbda91bbbad36e13763a71ed3f94f6e652054696d65204d696e7465722050726f64205b76696120436861696e50.json
Labels: checked, waiting for author
